### ISSUE TITLE
bintray latest version do not download latest version - download url for any automation script

### ISSUE THREAD

**Issue by babumuralidharan** [curl/curl-for-win#11]
### I did this
bintray url for latest version do not work for this url ->https://bintray.com/vszakats/generic/curl/_latestVersion
### I expected the following
when i click this url i always expect zip file to be download. Default 64 bit but need to have a way to to form the url for both 32(https://dl.bintray.com/vszakats/generic/:curl-7.71.1-win32-mingw.zip) and 64 (https://dl.bintray.com/vszakats/generic/:curl-7.71.1-win64-mingw.zip)

Ask his because we have an automation script that needs to download latest version of curl everytime. So that's why I'm placing this requst. Can you help understand the right way to download latest zip via an automation script
### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
The latest official curl for windows builds are provided at https://curl.haxx.se/windows/.

**Comment by vszakats** [comment]
I forgot to update the Bintray page, sorry. Sadly it's a manual process (at least I haven't found a way to automate it.)
Anyhow as said already, the official download URL is: <https://curl.haxx.se/windows/>
The value of Bintray is to retrieve historical versions. (Plus it's an advertised download site for OpenSSL binaries.)
