### ISSUE TITLE
does latest version support NTLMv2 for proxy authentication ?

### ISSUE THREAD

**Issue by geertn444** [curl/curl-for-win#14]
I see NTLM but i don't see any v2 flags.
curl 7.73.0

**Comment by vszakats** [comment]
geertn444: All I can say is that the `NTLM` feature is enabled in these builds, but I have no information about any NTLM details. If you think something is supposed to be implemented/enabled in curl, but doesn't work in this particular build, I suggest opening a new Issue about it with more details.

**Comment by vszakats** [comment]
Closing this for now.
