### ISSUE TITLE
curl-7.73.0_3-win64-mingw.zip has size 0.0 MB?

### ISSUE THREAD

**Issue by simon04** [curl/curl-for-win#15]
On https://curl.se/windows/, the file https://curl.se/windows/dl-7.73.0_3/curl-7.73.0_3-win64-mingw.zip is listed with Size: 0.0 MB

**Comment by vszakats** [comment]
Indeed, I also noticed it, but the linked file is the correct one.

Assuming this was something transient, I'm pushing a revision trying to fix this.

**Comment by simon04** [comment]
Thank you for the instant fix! :smile:

**Comment by vszakats** [comment]
You're welcome! But, it didn't fix it; now the 32-bit version appears as zero size. Can't readily [see](https://github.com/curl/curl-www/tree/master/windows) what may be the problem. One thing definitely changed with `7.73.0_3`: Now each `.zip` and `.tar.xz` file comes with a GPG signature with a `.asc` suffix in their filenames.

**Comment by vszakats** [comment]
It looks like the fix worked for the latest pushed revision. Closing this for now. Thanks for the report!

**Comment by bagder** [comment]
:tada:
