### ISSUE TITLE
PowerShell issue

### ISSUE THREAD

**Issue by 89z** [curl/curl-for-win#17]
If I run this command, I get success:

~~~
PS C:\> C:\windows\system32\curl -d '{""north"": ""east south""}' `
>> https://reqbin.com/echo/post/json
{"success":"true"}
~~~

If I run the same command with cURL from here:

https://curl.se/windows

I get error:

~~~
PS C:\curl-7.75.0-win64-mingw\bin> .\curl -d '{""north"": ""east south""}' `
>> https://reqbin.com/echo/post/json
curl: (6) Could not resolve host: east
curl: (3) unmatched close brace/bracket in URL position 6:
south} https://reqbin.com/echo/post/json
     ^
~~~

**Comment by vszakats** [comment]
@89z: I'm afraid I won't be able to answer why the PowerShell command-line quoting behaviour in MS-shipped curl behaves differently than the one built here. It may have something to do with the compiler used (mingw here, likely some MSVC version in case of Windows), different C RTL used, different build settings (Unicode vs. non-Unicode?), possibly an MS-specific patch that is used in the bundled binary, or some extra magic that is required for PowerShell inside Windows-specific command-line handling code.

Referring to this issue, which appears similar:
https://github.com/stedolan/jq/issues/1377

**Comment by 89z** [comment]
I found this as a workaround:

~~~
curl.exe --trace-ascii asdf -d '{\"north\": \"east south\"}' https://reqbin.com/echo/post/json
~~~
