### ISSUE TITLE
Default branch name should be master not main

### ISSUE THREAD

**Issue by jay** [curl/curl-for-win#19]
We use master everywhere in the org but this repo

https://github.com/curl/curl-for-win/settings/branches

**Comment by vszakats** [comment]
I use main everywhere, and don't plan to change this. Sorry!

**Comment by jay** [comment]
? Nothing is stopping you from doing that but why did you change it on the organization repo? You know we use master everywhere. I don't see any discussion surrounding this.

**Comment by vszakats** [comment]
I also haven't found any guidlines that would prohibit changing the default branch name, or specifically prohibit using `main`. Besides, I've been the only one ever committing here, so I assumed it wouldn't bother anybody. In fact it's rather surprising this is FIRST EVER feedback I got for curl-for-win from any curl contributor. I've also been preparing for this change for at least [6 months](b23f03d9929bca02cb32dfcf80f4e3819a449c6b) and nobody ever raised it as an issue. I also can't see how this would affect any curl users or even developers. Am I missing something here?

Having said, I've glad to pass on maintenance of this repository to anybody interested. First, I'd prefer to stay out of scolding like in this Issue, seconds, I've stopped using these curl builds about two years ago.

So, please let me know if this is a critical issue and if somebody is willing to continue this work with whatever branch name is preferred.

**Comment by jay** [comment]
My clone failed to fetch, I don't know if this was the cause. I ended up forking and saw you changed it to main. I still don't understand why you did it but ok. I appreciate your work, and you've basically been carrying this so I'll close.

**Comment by vszakats** [comment]
There is nothing particularly interesting about why I changed it: I never liked "master" that came with Git and find "main" to better describe the purpose and _shorter_ and easier to type. Minor downside is that it may be little less useful when grepping, but in practice the effect is likely negligible for most projects.

I'm sorry for causing some trouble for you as a result. It is true that sandboxes need to be updated when the default branch is renamed upstream. Here are the [steps to do it](https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/):

```
git branch -m master main
git push --set-upstream origin main
```

Or, just delete the sandbox and `git clone` again.
