### ISSUE TITLE
no UNICODE windows build

### ISSUE THREAD

**Issue by 2i-mh** [curl/curl-for-win#24]
While dependecies like openssl are compiled with `-DUNICODE`, the actual curl library itself isn't. This means international domain names can't be used with these builds.

**Comment by vszakats** [comment]
Unicode support in curl is incomplete, undocumented and seemed broken in may places, so a while ago I made the decision to disable it for now. See more details in this [commit](https://github.com/curl/curl-for-win/commit/bb029053639336c64d103fc97c8e33a495df20f1). Hopefully this can be re-enabled once the issues are fixed and a way to help that is to address the related PRs and Issues.

(I haven't tried, but international domains can probably be used by passing them in Punycode form.)
