### ISSUE TITLE
WinGet

### ISSUE THREAD

**Issue by sirinath** [curl/curl-for-win#26]
Can this be added to WinGet

**Comment by vszakats** [comment]
As far I know [^1] WinGet needs MSIX package format and a non-self-signed code signature. If this is so, this package as is now does not support either of these and adding them isn't possible (code signatures may break reproducibility and also need money) and/or need significant effort (manual signature management and cross-building MSIX formant, where it is unclear if the latter is possible or not). But, maybe WinGet maintainers can give a better answer.

[^1]: Which may be completely wrong, as I haven't followed the WinGet project.

**Comment by vszakats** [comment]
Closing this for now, but feel free to comment or discuss if there is some new information regarding this topic.
