### ISSUE TITLE
Add a way to download the latest version at all time

### ISSUE THREAD

**Issue by Eijebong** [curl/curl-for-win#27]
Hey, would be nice to have a download link always pointing at the latest release for automated jobs. `7.79.1_4` just disappeared breaking some CI jobs for me. This isn't the first time this happens. I see from #11 that there was a way to do so but bintray seems to have been remove a while ago and I couldn't find anything on https://curl.se/windows that would point me to a latest binary.

**Comment by bagder** [comment]
A fair idea! :+1:

**Comment by Eijebong** [comment]
(Would even be better if the version was changed within the zip file or removed so it wouldn't be a pita to add it to the PATH)

**Comment by vszakats** [comment]
@bagder: This looks like the best solution!

As for removing versions from internal paths, I'm not in favour, but the `tar --strip-components` can resolve it cleanly when unpacking. Also, `unzip -j curl-win64-latest.zip "*/curl.exe"` can get the self-contained .exe, or `unzip -j curl-win64-latest.zip` the complete, flat content of the zip.

**Comment by bagder** [comment]
We should probably add those links to https://curl.se/windows/ as well, I'm just not sure exactly how/where.

**Comment by vszakats** [comment]
One option is to add the current versioned curl links to a topmost, new `curl` line to the "Specifications" section and changing the header slightly:

`curl 7.81.0 was built and statically linked with` → 
`curl 7.81.0 versioned links and dependencies`

Then replace the versioned main links with the unversioned ones in the 'Packages' section. ...not perfect, I'd personally prefer versioned links as the primary ones, plus this makes it less clear how the depencencies and the main curl package are related.

Or, maybe just add a new section 'Direct links to the latest version' with the two new links?

**Comment by bagder** [comment]
Links added. Case closed!
