### ISSUE TITLE
Where to download 'openssl-1.x.x-win64-mingw.zip'

### ISSUE THREAD

**Issue by zjsunzone** [curl/curl-for-win#31]
Hi,
  Where can i  download 'openssl-1.x.x-win64-mingw.zip', please? It's very import for me.

**Comment by vszakats** [comment]
Apparently all archives of these (known to me) have been deleted, and the 1.1.1 line isn't updated here anymore. You can roll back this source repo to [~7 month ago](https://github.com/curl/curl-for-win/commit/2fb8b5ba0980996bb04d5a779457e45390abe6bc) and run the build locally, which would normally produce this binary.

**Comment by bagder** [comment]
1. We remove old packages to save disk space
2. I don't think the curl website is the best place to store nor look for OpenSSL packages

**Comment by vszakats** [comment]
One more thought: Even if the latest 1.1.1 binaries (v1.1.1l) built by this project would be available somewhere, it would not be the best idea to use it, because there have been (as of today) two vulnerability patch releases since that version.
