### ISSUE TITLE
Entry Point Not Found: AcquireSRWLockExclusive (KERNEL32.DLL)

### ISSUE THREAD

**Issue by Fierelier** [curl/curl-for-win#32]
### I did this

I downloaded the newest build from https://curl.se/windows/, and ran the exe. I received the following error: The procedure entry point AcquireSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll. I suspect the latest version caused this.

### curl/libcurl version

curl-7.81.0-win32-mingw

### operating system

Windows XP Professional Service Pack 3 (5.1.2600)

**Comment by Fierelier** [comment]
I did the same test on Windows 10 Home 21H2 (19044.1288) 64-bit with success. I'll do the same with W11 as well.

**Comment by Fierelier** [comment]
Actually, I'm burnt-out as-is with installing W10, I reckon it oughta run on W11.

**Comment by vszakats** [comment]
Thank you @Fierelier, I think this is fine for now. I'm more worried of future fallouts due to stepping off the default build path; so pushing this patch on an experimental note.
