### ISSUE TITLE
Curl 7.85/32Bit not a valid Windows application

### ISSUE THREAD

**Issue by cscode2000** [curl/curl-for-win#37]
Starting with Curl 7.84 an error message occurs in Windows XP, that it isn't a valid application. Also with newest curl-7.85.0_1-win32-mingw.zip
curl-7.83.1_2-win32-mingw.zip works.

**Comment by vszakats** [comment]
After announcing it a few months ago, we dropped XP support with 7.85.0. Starting with this version it requires Vista. So this is expected.

Relevant commit with more info: 6976612160075c1e9ee967964d5dec1a25c5ac6c
Announced on the front page here: 8d55c0d62e29d44776eb40c7b3c57973426798b3
