### ISSUE TITLE
libcurl Static link instructions and/or pkg-config file

### ISSUE THREAD

**Issue by avih** [curl/curl-for-win#39]
Hi,

I'm trying to build [txiki.js](https://github.com/saghul/txiki.js) on debian 11 using the mingw distro toolchain, linked with https://curl.se/windows/latest.cgi?p=win64-mingw.zip (currently `curl-7.86.0_2-win64-mingw.zip`), and couldn't quite figure out what I should link with.

First, is there some README file at the zip or elsewhere which instructs how to use libcurl at the zip? If there is one, hopefully it answers at least some of the subjects below.

I first tried linking with `libcurl.dll.a`, which worked, and the resulting binary requires the curl dll (as expected). So that's a success.

I then wanted to instead link statically with `libcurl.a`, and encountered several missing libcurl symbols. After some searches I realized I needed `CURL_STATICLIB` defined, and I then used it successfuly.

Then it ended up with many (non-libcurl) missing symbols, but couldn't find which libs it depends on. I tried this list `-lcurl -lz -lcrypt32 -lbcrypt -lwldap32 -lnghttp2 -lssh2 -lgsasl -lssl -lcrypto -lbrotlidec -lbrotlicommon -lzstd -lnghttp3 -lngtcp2` which appears at this repo README for the "Default build with OpenSSL and Schannel", but it failed with undefined reference to `ngtcp2_crypto_openssl_configure_client_context` and few more.

I added `-lngtcp2_crypto_openssl` which resolved this, but now I had a missing reference to `zlibVersion` and `inflate` and few more, so I moved `-lz` at the list to the end:
```
-lcurl -lcrypt32 -lbcrypt -lwldap32 -lnghttp2 -lssh2 -lgsasl -lssl -lcrypto -lbrotlidec -lbrotlicommon -lzstd -lnghttp3 -lngtcp2 -lngtcp2_crypto_openssl -lz
```

It then failed with undefined references to `__imp___sys_nerr` and `__imp___sys_errlist`, so (after some more googling) I added `-lucrtbase` to the list.

This seem to resolve all the undefined references, however, it then failed due to `SHA1` defined multiple times, first at the txtki.js sources, and then at `libcrypto.a` (`libcrypto.a(libcrypto-lib-sha1_one.obj):sha1_one.c:(.text+0x70): multiple definition of 'SHA1'; <the original definition location>`).

I'll need to think what to do about it, maybe rename it at the txiki.js sources.

Seeing that the question of static linking has been asked more than once, and that the generic FAQ doesn't say much about it (docs/FAQ "2.1 configure fails when using static libraries"), I think it could help to have some info specific to this zip distribution about static linking. Specifically:
- pkg-config file or some other up-to-date list of libraries to link with, especially for static linking with `libcurl.a` inside this zip (shared is relatively simple).
- Mention `CFLAGS=-DCURL_STATICLIB` or some such which is needed for static linking (not sure if this is windows only?).
- I _think_ it's possible to create a `libcurl.a` which embeds all the other static dependencies (similar to how the dll is linked statically with its deps), which could solve many issues (deps list, symbols which the project might not be expecting, etc).
- Consider mentioning (regardless of static/shared) that unlike a typical linux/*nix setup, `https` WILL fail because it defaults to OpenSSL but without a default ca bundle (embedded/at some path), unless one of the following happens (I think):
  - Curl is initialized with a path to ca bundle, e.g. using `curl_easy_setopt(curl_h, CURLOPT_CAINFO, "curl-ca-bundle.crt");` and then put this file at the same dir as the binary (seems to work, but I couldn't find docs for the search dirs of CURLOPT_CAINFO if it's not an absolute path, and also not what to do about unicode paths - does it expect UTF-8?).
  - Or switch to schannel at runtime (one liner could help, if it exists).
- Consider a default configuration where https works out of the box without specific runtime setup? I've read several discussions about it, and I think OpenSSL is recommended over schannel, but maybe try some fixed ca bundle file name (`curl-ca-bundle.crt` is used by `curl.exe` at the zip, so I thought it could be a default name for libcurl at the zip as well), and fallback to schannel if it's missing?

**Comment by vszakats** [comment]
@avih: Thanks for your post. I understand your pains with static linking. You summed up very well what issues can be expected and how to fix them.

However, besides the informal `Libs:` lines in the README, I don't plan to maintain comprehensive documentation or special support for static linking (such as `pkg-config` or a "fat" `libcurl.a`). Simply for lack of time and interest. Such need to be kept in sync (and tested) with the full range of ever-changing bits of curl builds, possibly also considering the combinations this repo supports and varying toolchain needs (e.g. regarding UCRT).

Two suggestions that may help jumping through this:
- Use the lib list as-is from our build log when it's linking `curl.exe`.
- Look into `lib/Makefile` in the curl repo which should pick the correct `LIBS` in the correct order for static linking. (at least for common configurations)

I've also added the ngtcp2 crypto lib to the `Libs:` lines in the README following your suggestion.

Some points are not specific to these binaries, so may have a better place in the main curl repo. Some of them are already there, e.g. `CURL_STATICLIB` in `docs/INSTALL.md`.

As for what supports UTF-8, this is an open issue on Windows, and "it depends". It's not officially documented in curl. See also: <https://github.com/curl/curl/wiki/libcurl-and-expected-string-encodings>.

OpenSSL [recently got](https://github.com/openssl/openssl/commit/606e0426a148034c8c131de9f31f7d3e38be99ea) support for built-in Windows certs. I haven't looked into it, and it might not made it to a release yet. It will resolve this faster then waiting for Schannel to catch up with OpenSSL features. Having said that, the `mini` and smaller builds all use Schannel by default. You can use them if you're ready to build your own curl-for-win.

**Comment by vszakats** [comment]
Sure, these builds are the "official" curl builds for Windows. We even link there from here.

By all means you're welcome to create such document.

My concern is keeping it up to date. It feels like a huge effort, over the already huge effort curl-for-win takes.

But, if the document is useful, we can link to it from here, or from other pages. It may even fit curl's INSTALL/FAQ docs, which already mentions static linking. (There is also `winbuild/README.md` for MSVC.)

**Comment by vszakats** [comment]
Ref: https://github.com/curl/curl/pull/9944

**Comment by avih** [comment]
> My concern is keeping it up to date. It feels like a huge effort, over the already huge effort curl-for-win takes.

Agreed.

> It may even fit curl's INSTALL/FAQ docs, which already mentions static linking

The FAQ maybe, but as far as I can tell INSALL explicitly does not refer to using the curl binary distribution, and does refer to building curl from source - same as [curl/curl#9944](https://github.com/curl/curl/pull/9944)

What I had in mind is exactly these two parts:
1. Mention https doesn't work unless FOO. I don't think this part can be automated, and it will be in effect, if I understand correctly, as long as the configuration defaults to OpenSSL (or some other backend which depends on a ca bundle), but the default CURLOPT_CAINFO is NULL, correct? If so, maybe some comment can be added to the Makefile/whatever of this configuration to update this document if it changes?
2. How to link statically with libcurl. I feel the main tool for that should be a pkg-config file, and this document should only have notes about it, if any. The reason I think pkg-config is because the info exists when buildng the zip (probably almost exactly the same list of libs used for linking `curl.exe` inside this zip), and (i'm guessing) almost all distros create one when they build libcurl, so a useful procedure to create a pkg-config file surely exists someplace.

**Comment by avih** [comment]
(I've not built libcurl myself) does building libcurl generate a pkg-config file in general? It looks like it does - the main repo has `libcurl.pc.in`, and `CMakeLists.txt` does seem to use it to generate a pc file.

Does it not get generated when building libcurl-for-windows using this repo? If it is generated, why is it not packaged at the zip?

**Comment by vszakats** [comment]
These builds use bare GNU Make and don't generate `pkg-config`.

Alternate CMake and autotools builds do, though at least the latter generates them with multiple issues (missing CFLAGS, hardcoded absolute paths). I've found `pkg-config` generally unusable on Windows, introducing more issue than solving (in fact I have to purge them while doing these builds to make it work). So no, no `pkg-config` support. But, if you do a local build with CMake (or autotools) there will be one generated.

**Comment by vszakats** [comment]
Regarding the CA: Perhaps this information would fit best inside curl somewhere, the FAQ maybe, or libcurl docs? It's a general issue when using llibcurl + any TLS backend that doesn't read the OS CA store. Maintaining a list of these TLS backends / versions would also be useful.

**Comment by avih** [comment]
> the FAQ maybe, or libcurl docs?

Probably, but regardless, I do feel strongly that the zip should include some notes specific to this distribution. Like listing the build options, maybe build logs, and the two subjects I mentioned above.

I can think of at least one doc which could be updated - https://curl.se/libcurl/c/CURLOPT_CAINFO.html . It wasn't obvious to me that it can be empty by default. It is stated that it depends on the build config, but hard to guess that an empty default is actually a viable distributable config.

**Comment by avih** [comment]
re 871a25b8d9c67e1857a830eb6ec9a0a289b787ff , as far as I can tell `-lz` should be after `-lssh2`, or else it fails for me.

Also, why `-lucrt` (or ucrtbase) not added to the README?

**Comment by vszakats** [comment]
Because it's not true when using for example mingw-w64 (which has a convoluted method to override msvcrt, last time I checked). As for `-lz`, I prefer to keep the current layout for editability and human readability, and just cannot guarantee any particular order there. In fact it might be best to delete those `Libs:` lines as it's already a hassle to keep up-to date. And even failing at that, so it only causes confusion even in its current form.

IMO the best indication of the necessary libs is the actual list of `.a` files shipped inside the distro package. All of those are required. The generic solution to make them link regardless of ordering is to enclose them between `-Wl,--start-group` and `-Wl,--end-group` linker options. This is non-fragile and maintenance free.

Including logs (or even links to logs) break reproducibility, making every build producing a different hash, so that's not workable sadly. So instead we link to the log from the [download page](https://curl.se/windows/).

I agree that CA bootstrapping details would be nice to have on the `CURLOPT_CAINFO` page.

**Comment by avih** [comment]
I see. I think this means that no readme should be created/updated, and that there are two todo items outside the scope of this issue: improve CURLOPT_CAINFO docs (default can be empty, non-absolute paths search dirs, UTF-8), and maybe improve the CA bootstrap implementation/configuration so that https works out of the box for libcurl without additional setup compared to *nix?

I this case, I'll just summarize the info here for posterify (and then you can close it and/or help me improve it, or both, or edit it yourself, or whatever).

---------------------

These notes refer to using the mingw libcurl as distributed at https://curl.se/windows/ as of version 7.86.

This libcurl supports both OpenSSL and Schannel TLS backends, and defaults to OpenSSL - which needs a CA bundle file. However, a default CA bundle path is not configured, and so by default https will fail. Possible solutions:
- Configure a CA bundle path, for instance `curl_easy_setopt(curl_h, CURLOPT_CAINFO, "curl-ca-bundle.crt");`. This is the same bundle name which `curl.exe` inside this zip uses by default, and this file is available at the distribution package. Without an absolute path - the file is searched (at least?) at the executable directory. If an absolute path is used instead, and this path might contain non-ASCII7 chars, then the `char *` value for CURLOPT_CAINFO path should be UTF-8 (see also [string encodings](https://github.com/curl/curl/wiki/libcurl-and-expected-string-encodings)).
- Switch to Schannel TLS backend. (TODO: example one liner?)
- The default behavior might change in the future so that https does work by default. Check the release notes of future versions.

It's recommended to link with libcurl dynamically - with `libcurl.dll.a`, and place the curl dll from the zip at the same dir as the binary.

Static linking is also possible, but less simple. Some notes:
- `CURL_STATICLIB` should be defined before including `curl.h`, for instance, by adding `-DCURL-STATICLIB` to `CFLAGS` (assuming the build system applies `CFLAGS`).
- a `libcurl.pc` pkg-config file is _not_ provided, and yet you'd need to link with several additional (static) libraries in addition to `libcurl.a`. The list of libraries are all the `lib/*.a` files inside the zip, except `libcurl.dll.a`. Their order can be important - depending on other linker options:
  - When plainly linking with the libraries using `-lcurl -lfoo -lbar...`, at the time of writing the list and order is `-lcurl -lcrypt32 -lbcrypt -lwldap32 -lnghttp2 -lssh2 -lz -lgsasl -lssl -lcrypto -lbrotlidec -lbrotlicommon -lzstd -lnghttp3 -lngtcp2 -lngtcp2_crypto_openssl`, and you may need to add `-lucrt` depending on the mingw configuraion.
  - One way to automate it is to extract the list of `-lfoo -lbar` by parsing the `lib/*.a` files at the zip, and then place this list between `-Wl,--start-group` and `-Wl,--end-group` linker options.

Example (posix) `sh` script to automate the static link flags (starting at the zip root directory):
```sh
LIBS="-lcurl -Wl,--start-group"
for f in ./lib/*.a; do
    case $f in *curl*) continue; esac
    f=${f##*/lib}; f=${f%.a}
    LIBS="$LIBS -l$f"
done
printf %s\\n "$LIBS -Wl,--end-group"
```

**Comment by vszakats** [comment]
Few more, potentialy interesting points:
- Regardless of static/dynamic linking, it's important that the host application also must be compiled with UCRT enabled.
- Pointers to the build log and `lib/Makefile.mk` in curl.
- List of necessary Windows systems libraries. This can be read from `lib/Makefile.mk` for example.
- `pthread` lib is not currently needed, but may be necessary once we switch to BoringSSL. Also pending a pthread vs UCRT bug in most/certain mingw-w64 toolchain builds.
- Not a one-liner but `curl_global_sslset()` is the libcurl function to switch TLS backends at runtime.
- It's perfectly normal and expected that a library with dependencies will always require more than a single library when linking statically. I think the wording should not be alarmist about this.

Applies to current default official builds. curl-for-win allows to toggle certain features (e.g. UCRT), toolchains and dependencies.

**Comment by avih** [comment]
> Few more, potentialy interesting points:

Thanks. except as noted below, I'll leave them as additions in your own post, because you know about them (log links, etc) more than me.

> * It's perfectly normal and expected that a library with dependencies will always require more than a single library when linking statically. I think the wording should not be alarmist about this.

I've edited it. better?

**Comment by vszakats** [comment]
@avih: Can you describe how would you use a `libcurl.pc` pkg-config file if there would be one?

**Comment by vszakats** [comment]
I understand.

Well, yeah, these have many problem. I haven't even looked at `Libs:` vs `Libs.private`:
- Missing `-DCURL_STATICLIB`. (cmake)
- `.a` files with absolute paths. (cmake)
- Toolchain-specific low-level libs. (cmake)
- Hardcoded "prefix", where prefix has no meaning on Windows. (both)
- Duplicate libs. (both)
- Missing libs (e.g. `pthread`, due to the way I had to force feed it to `libtool`) (autotools)
- Incomplete feature list (due to broken HTTP3 lib detection and the manual method of enabling it) (autotools)
- Possibly confused `Libs:` vs `Libs.private:`. (both)
- Possibly more.
- No `libcurl.pc` generated at all. (gnumake aka `Makefile.mk`)

Some of these are fallouts from build tricks I need to use, some others are cmake/autotools "things", and some others are `pkg-config`-specific design choices, like the insistence on well-known/hardcoded paths, which do no exist on Windows (outside MSYS2 and similar sub-envs).

Anyhow, if you manage to settle on a well-working `libcurl.pc` (preferably not just with CMake, but a bare linker command-line) we might use this to generate a usable one in the future. For sure it'd be useful, but I'm not confident that this is a achievable goal.

**Comment by vszakats** [comment]
Your summary is on point. The target for these libs is indeed "limited" considering the almost infinite variations of lib formats, ABIs and other variations these can come on Windows. (I find this quite sad toolchain landscape and not a single bit better than say 15 years ago.)

In short, this might be useful for someone using mingw-w64 or llvm-mingw, either gcc or llvm/clang, who might want to link to a libcurl that isn't bound to any specific unixy environment, such as MSYS2, either dynamically, statically or via any other assumptions of these envs. Perfect to ship a standalone Windows .exe, also from a non-Windows env via a cross-build, if that's someone's thing.

MSVC never was a goal for these builds. Nor was Cygwin. And MSYS2/friends, as you said, already offer their own curl packages, though those I've found not really suitable for shipping your own app binaries.

But, yes, nowadays the main goal is to provide `curl.exe`. I have no stats, not even download numbers, but that's probably what most people use. Then possibly the DLL, which is somewhat more easily pluggable into other envs, then probably just a few who actually use the static libs.

Having said that, the original aim of these builds was in fact to provide the static libs! Now it's the byproduct. [ I still have a somewhat idle project that expects these libs. For my own purposes I switched to `pico` builds to keep it simplest. ]

**Comment by avih** [comment]
> Then possibly the DLL, which is somewhat more easily pluggable into other envs. Then probably just a few who actually use the static libs.

Right, FWIW, the txiki.js project vendors few sub-projects (git submodules) which it builds and links statically with, and expects libcurl to exist someplace. It does not depend on further libraries.

I was trying to create a semi reproducible mingw build env, and I used a debian live dvd with the mingw toolchain installed from the distro packages after boot, and then needed only libcurl to complete the build deps, where the one from https://curl.se/windows/ was just what the doctor ordered ;) Even with the shared dll I consider it a good success, and to be honest, I did not expect it to work.

I didn't even realize initially that it includes development files, as in the past I only used it for the `curl.exe` binary (and libcurl recipe/package always existed at my mingw envs).

So it can have real-world use cases, and also serves as a reference to $something. But yeah, OSS/posix build envs for windows are such a pain...

> the original aim of these builds was in fact to provide the static libs!

Maybe revive that with a "fat" `libcurl.a` static lib for mini/pico config? :)

**Comment by vszakats** [comment]
I'm glad this could fit into your project, and it's something nice to hear.

[ I find "mingw-w64" working rather well, and `llvm-mingw`, which is fantastic. Also the fact that these toolchains are now ubiquitous on popular platforms. A definite improvment over the years. And LLVM/clang. The binutils tools need some getting used to and had/have to deal with Windows-specific bugs. Most of them obscure. Fixes take years to propagate to releases. But, the knowledge is in large part portable, which I find useful.

What's lacking on Windows in general is standards or conventions even. No ABI, filename, dirname, lib format, or anything has any standard. Especially with MSVC which doesn't even have proper C99 support (or by now it has?). Making a cross-vendor DLL is a pain (it used to be with mingw-w64 at least). Thus, everyone keeps guessing and nothing is reusable. Microsoft could change that, but why would they? ]

Building for Windows is in effect like building for 4-8-16-64 distinct platforms, depending on settings, compiler vendor, version, make tool and whatnot, where the only thing in common is the Win32 API and the PE .exe format.

Though "fat" static lib seems doable technically, it's a step back for reproducibility and transparency IMO. Which is a question of convention, because for DLL and EXE a huge binary is okay, but for static libs, it seems unusual.

Maybe an opportunity to create such script and publish it as a Gist for those interested.

**Comment by avih** [comment]
> I find "mingw-w64" working rather well, and `llvm-mingw`, which is fantastic

I presume that by "mingw-w64' you refer to the toolchain sources here https://www.mingw-w64.org/ which most mingw setups use these days, and not to a specific set of binaries, right? (agreed)

And that by "llvm-mingw" you refer to the project and a specific set of binaries here https://github.com/mstorsjo/llvm-mingw ? how do you use it? from an MSYS2 setup with the path modified to include the bin/ dir, and then cross compile using its various prefixes?

> [rant]...

Agreed :)

**Comment by vszakats** [comment]
Yes, that's what I meant by mingw-w64 and `llvm-mingw`.

I've found `llvm-mingw` the easiest and it also works indentically on all platforms. Unpack, point `PATH` to the `bin` dir, select a prefix (or use the full path + triplet as a prefix probably works too), and it's good to go. [ If you don't insist on clang and UCRT, a pure mingw-w64 toolchain should be similarly easy. ]

If you're interested, the toolchain setup happens in `_build.sh`. Look for the word `llvm-mingw`.

In fact this is the only toolchain that doesn't bump into the static winpthread + UCRT bug, so the only one able to create BoringSSL builds.

llvm strip tool has some (niche) bugs, so for proper sripping the binuntils strip is necessary. You can ignore that if reproducibility across platforms isn't your goal.

**Comment by avih** [comment]
> * Regardless of static/dynamic linking, it's important that the host application also must be compiled with UCRT enabled.

Actually, I _think_ this mostly only applies to static linking.

Judging from my own anecdotical experience, linking with the shared dll passed all txiki.js tests, but linking statically (after working around the roadbumps) failed some tests. I didn't mention it here because I thought I'm still doing something incorrect with the linking.

But then I saw https://www.msys2.org/docs/environments/#msvcrt-vs-ucrt which mentions:
> Binaries linked with MSVCRT should not be mixed with UCRT ones because the internal structures and data types are different. (More strictly, object files or static libraries built for different targets shouldn't be mixed. DLLs built for different CRTs can be mixed as long as they don't share CRT objects, e.g. FILE*, across DLL boundaries.) Same rule is applied for MSVC compiled binaries because MSVC uses UCRT by default (if not changed).

I'm not familiar with the libcurl API, but I'm guessing it's not passing `FILE*` pointers across library boundary?

**Comment by vszakats** [comment]
There are a couple of libcurl functions that can exchange `FILE *` pointers (e.g. `CURLOPT_WRITEDATA` and co, `curl_mfprintf()`, etc.). It's fairly easy, but you need to take care to avoid those.

Question what else may be affected, because the above quote cites `FILE *` as just one example. But sure, if you're certain to not be affected, the DLL can be mixed with non-UCRT.

**Comment by avih** [comment]
> There are a couple of libcurl functions that can exchange...

Right, then I guess txiki.js either does not use them, or does not use them in tests, or by luck no issues were observed.

Generally speaking though, it seems that a UCRT libcurl should not be used with msvcrt application (which is how I compiled txiki.js for now), because even if today it doesn't use such APIs, tomorrow it might.

> Question what else may be affected

I'd imagine any libc objects which are created with one crt and are manipulated/used at the other, like FILE* objects, malloc in one and free/realloc at the other, etc.

**Comment by vszakats** [comment]
Yeah, the sure way is not to mix CRTs.

One thing for consideration is using UCRT instead of msvcrt. I might have missed stuff here, but to me it seemed that unless you need to target XP and especially older Windows versions, UCRT is fine. As for open-source tooling: mingw-w64 hopefully will make it easier to enable it and remaining bugs will also be ironed out, such as the static winphtread one.
