### ISSUE TITLE
Text files are not viewable in notepad

### ISSUE THREAD

**Issue by jay** [curl/curl-for-win#42]
I downloaded curl-7.87.0_1-win64-mingw.zip and the text files have LF instead of CRLF line endings and are not viewable in notepad. Here's a screenshot from a Windows 7 VM. (ignore the chinese text it's for a bug where I needed to switch locale)

![Capture](https://user-images.githubusercontent.com/965580/211265599-76603848-6e7a-4a0e-beb9-e0cc16891080.PNG)

**Comment by vszakats** [comment]
Windows 10 is supposed to be supporting LF EOLs, according to this: https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/

Windows 7 is not supported anymore by MS. Adding these two, I made the decision that it's not worth to convert everything to CRLF for the sake of old Windows systems. So far nobody complained. I think it's also a reasonable workaround to change the default text viewer to an alternative that copes with LF EOLs. Overall, I prefer not altering any original/input files, unless absolutely unavoidable.
