### ISSUE TITLE
Openssl 1.1.1s or q

### ISSUE THREAD

**Issue by MDzyga** [curl/curl-for-win#45]
Hi,
I would like to ask you if you plan to release openssl 1.1.1q or s in zip format or you know where I can find it?
Unfortunately I'm not able to use openssl 3.0.X because it requires TLS 1.3 and my server doesn't support it.

**Comment by vszakats** [comment]
@MDzyga No, sorry, we don't provide anything older than the latest stable release.

In general, 3.0.x should be fine if your server supports TLS 1.2 (instead of 1.3).

**Comment by MDzyga** [comment]
Thanks, version 1.1.1s is one of the latest (2022-Nov-01) ;) 
Do you have some instruction how I can prepare zip file from the pakcage distributed by Openssl?

**Comment by vszakats** [comment]
You're free to have a different definition of _latest_. This project [switched to](307778487f585d718df75880eeb1a1653f482640) 3.0.0, when it was released, in 2021.

This project is a curl binary distribution that merely uses OpenSSL as a dependency. We don't do OpenSSL instructions and stopped offering a complete package of the dependencies we use. These may be answered by OpenSSL itself.
