### ISSUE TITLE
Url for specific version is down

### ISSUE THREAD

**Issue by Brubbish** [curl/curl-for-win#52]
Hi, I'd like to download other version of curl, but found that the curl.se site seems don't have the resources.(e.g. https://curl.se/windows/dl-8.0.1_4/ shows 404 error)

Also, is there a way to obtain the debug version, if so, it would be nice.

**Comment by bagder** [comment]
[https://curl.se/windows/](https://curl.se/windows/) provides the latest the latest curl version for download.

It does not offer an archive of old versions, which is why no old versions are linked to. Old versions are removed.

> Also, is there a way to obtain the debug version, if so, it would be nice.

What do you want to do with a debug version?

**Comment by vszakats** [comment]
I've updated the latest available older build in `README.md`. I'm also open to delete that link altogether. Up to a certain point, previous builds may useful when checking for regressions. For production, the latest is the best.

Older binaries can also be downloaded from the AppVeyor CI build jobs' artifact page for 6 months.

We don't plan to publish debug builds, as these come with zero security so not fit for production. It's seldom tested, but curl-for-win is able to build those when enabled in a private fork or on a local machine (with the `-debug` option).

**Comment by Brubbish** [comment]
Thanks guys. Actually, I intended to reproduce the result in a scientific paper about software analysis that uses debug version executables to extract static information. I think I may have to build the debug version myself then.

**Comment by bagder** [comment]
> I've updated the latest available older build

Thanks. I don't want to keep hosting all builds forever on this server, so I intend to keep pruning the set every once in a while to focus on the latest versions.

**Comment by vszakats** [comment]
That's okay I think. One way to automate this would be having a root URL with all offered past versions (subdirs). That would allow linking to that root URL from the README.

We already link to the AppVeyor CI job history page, but that's less user-friendly due to the (occasionally many) non-main branch builds mixed onto that list. I've found no way to link to the main branch history only.

**Comment by CHN-STUDENT** [comment]
hey, you mean if i need old version, i need to build by myself? we have win7,server 2012 some old version os computer,the lastest  can not work normally.

**Comment by jay** [comment]
> we have win7,server 2012 some old version os computer,the lastest can not work normally.

As seen on the [download page](https://curl.se/windows/) the latest version of curl is supported on Windows 7 and I can confirm it works. It depends on Windows Universal CRT which should already have been installed by Windows Update or you can download [KB2999226](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c) manually from Microsoft.

If it does not work for you then please open a new [discussion](https://github.com/curl/curl-for-win/discussions) for help.

**Comment by CHN-STUDENT** [comment]
> > we have win7,server 2012 some old version os computer,the lastest can not work normally.
> 
> As seen on the [download page](https://curl.se/windows/) the latest version of curl is supported on Windows 7 and I can confirm it works. It depends on Windows Universal CRT which should already have been installed by Windows Update or you can download [KB2999226](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c) manually from Microsoft.
> 
> If it does not work for you then please open a new [discussion](https://github.com/curl/curl-for-win/discussions) for help.

oh, sorry , I get C CRT runtime error when i try to use curl for windows on our servers.  It seems need to install some patchs to make curl works. Because it is production environment and i only do simple http test. At last, i download the old version `curl 7.45.0 (i386-pc-win32) libcurl/7.45.0` from [here](http://bcn.bathome.net/s/tool/index.html?key=curl) , it can work without any patchs, thanks for your help!!
