### ISSUE TITLE
Non-latin symbols processing

### ISSUE THREAD

**Issue by squromiv** [curl/curl-for-win#56]
When I try to send a query/post a message with non-latin symbols, it results to non-readable characters in received data. Checked with [n8n](https://github.com/n8n-io/n8n), [Apprise](https://github.com/caronc/apprise-api) and [HTTPDebugger](https://www.httpdebugger.com/).

Test command

`curl.exe -X POST -d "title=Title&body=Body - ԱՅՈՑ ԱՅԲՈՒԲԵՆ" http://server/notify/service`

Result

![245377870-016ab63f-5388-4758-8669-1307eaef2180](https://github.com/curl/curl-for-win/assets/15985877/4573774d-e0cb-40ff-8d84-19bbaa503d7e)
---
Windows Server 2016x64 Standard EN
Curl v. 8.1.1

**Comment by vszakats** [comment]
Not a curl-for-win issue. curl has limited/incomplete Unicode support on Windows.

**Comment by vszakats** [comment]
Update: You can work around this specific case by passing non-ASCII text via file or pipe for example.

**Comment by squromiv** [comment]
> curl has limited/incomplete Unicode support on Windows.

Is there any github issue in order to implement this feature? Or it is not planned at all?
